include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    inference_failure_on_function_return_type: ignore
    avoid_dynamic_calls: ignore
    use_build_context_synchronously: ignore
    argument_type_not_assignable: ignore
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    only_throw_errors: ignore
    implicit_dynamic_method: ignore
    always_use_package_imports: ignore
    avoid_slow_async_io: ignore

  exclude:
    # - lib/src/data/models/*.dart
    # - lib/src/data/models/utils/*.dart
    # - lib/src/data/network/*.dart
    # - "**/*.g.dart"
    # - "**/*.freezed.dart"
    # - lib/ui/modules/characters/model/*.freezed.dart
    # - lib/ui/modules/characters/model/*.g.dart
    - lib/src/configurations/routes_import.gr.dart

  strong-mode:

linter:
  rules:
    public_member_api_docs: false
    unrelated_type_equality_checks: false
